services:
  - type: web
    name: flying-panda-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node src/app.js
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5000
